# Generated by Django 5.1.1 on 2025-09-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_id', models.CharField(max_length=20, unique=True)),
                ('bay_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StableDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(null=True)),
                ('first_trip', models.DateTimeField(null=True)),
                ('kilometers_ran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recently_maintained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stable')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stable_records', to='accounts.train')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('maintaince_certificate', models.ImageField(upload_to='maintenance_certificates/')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('progress', models.CharField(choices=[('completed', 'Completed'), ('waiting', 'waiting'), ('in_progress', 'In Progress')], default='waiting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bay')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='accounts.train')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_cerficate', models.ImageField(upload_to='fitness_certificates/')),
                ('rolling_stock', models.BooleanField(default=False)),
                ('signalling', models.BooleanField(default=False)),
                ('telecom', models.BooleanField(default=False)),
                ('issue_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('validy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_records', to='accounts.train')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding_firm', models.CharField(max_length=100)),
                ('impressions', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.ManyToManyField(related_name='branding_contracts', to='accounts.train')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
