# Generated by Django 5.1.1 on 2025-09-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_testimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingcontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
