# Generated by Django 5.1.1 on 2025-09-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_brandingcontract_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessdepartment',
            old_name='signalling',
            new_name='braking',
        ),
        migrations.RenameField(
            model_name='fitnessdepartment',
            old_name='telecom',
            new_name='structural_integrity',
        ),
        migrations.AddField(
            model_name='fitnessdepartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
