# Generated by Django 5.1.1 on 2025-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_signalling_fitnessdepartment_braking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='progress',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='stabledepartment',
            name='kilometers_ran',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
