# Generated by Django 5.1.1 on 2025-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_progress_maintenance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessdepartment',
            old_name='rolling_stock',
            new_name='signal',
        ),
        migrations.AlterField(
            model_name='brandingcontract',
            name='branding_firm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brandingcontract',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandingcontract',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='brandingcontract',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='brandingcontract',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('INPROGRESS', 'inprogress')], default='waiting'),
        ),
        migrations.AlterField(
            model_name='stabledepartment',
            name='entry_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stabledepartment',
            name='kilometers_ran',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
