# Generated by Django 5.1.1 on 2025-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_rolling_stock_fitnessdepartment_signal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessdepartment',
            name='validy',
        ),
        migrations.AlterField(
            model_name='fitnessdepartment',
            name='braking',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessdepartment',
            name='expiry_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessdepartment',
            name='issue_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessdepartment',
            name='signal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessdepartment',
            name='structural_integrity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
