# Generated by Django 5.1.1 on 2025-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_fitnessdepartment_validy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AlterField(
            model_name='train',
            name='train_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
