# Generated by Django 5.1.1 on 2025-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_train_id_alter_train_train_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='parts_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technician',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_end',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_start',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
