# Generated by Django 5.1.1 on 2025-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_maintenance_parts_used_maintenance_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
