# Generated by Django 5.1.1 on 2025-09-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_maintenance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='bay',
        ),
    ]
