# Generated by Django 5.1.1 on 2025-09-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_maintenance_bay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingcontract',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brandingcontract',
            name='start_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='brandingcontract',
            name='train',
        ),
        migrations.AddField(
            model_name='brandingcontract',
            name='train',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='branding_contracts', to='accounts.train'),
        ),
    ]
