# Generated by Django 5.1.1 on 2025-09-16 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_brandingcontract_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kilometers', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('kilometers_ran_since_last_maintenance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('average_daily_kilometeres', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_mileage_for_the_period', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milage_records', to='accounts.train')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
