# Generated by Django 5.1.1 on 2025-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_certificates', models.BooleanField(null=True)),
                ('job_cards', models.CharField(max_length=20, null=True)),
                ('branding_priority', models.IntegerField(null=True)),
                ('current_mileage', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
