# Generated by Django 5.1.1 on 2025-09-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_modelchache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelchache',
            name='fitness_certificates',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
