# Generated by Django 5.1.1 on 2025-09-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_modelchache_fitness_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelchache',
            name='train_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='model_chache', to='accounts.train'),
        ),
    ]
